version: "3.9"

services:
  backend:
    build:
      context: ./Backend

    container_name: pujapath-backend

    ports:
      - "3000:3000"

    env_file:
      - ./Backend/.env

    restart: always

  frontend:
    build:
      context: ./Frontend

    container_name: pujapath-frontend

    ports:
      - "80:80"

    restart: always

    depends_on:
      - backend
