services:
  backend:
    image: mohammadayan7879/pujapathvedic-backend:latest

    container_name: pujapath-backend

    ports:
      - "3000:3000"

    env_file:
      - ./Backend/.env

    restart: always

  frontend:
    image: mohammadayan7879/pujapathvedic-frontend:latest

    container_name: pujapath-frontend

    ports:
      - "80:80"

    restart: always

    depends_on:
      - backend
