services:
  backend:
    image: mohammadayan7879/pujapathvedic-backend:latest

    container_name: pujapath-backend

    env_file:
      - ./.env

    restart: always

    networks:
      - app-network

    depends_on:
      - redis

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: pujapath-prometheus

    depends_on:
      - backend

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

    restart: always

    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: pujapath-grafana

    ports:
      - "3001:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    restart: always

    networks:
      - app-network

  frontend:
    image: mohammadayan7879/pujapathvedic-frontend:latest

    container_name: pujapath-frontend

    restart: always

    depends_on:
      - backend

    networks:
      - app-network

  nginx:
    image: nginx:alpine

    container_name: pujapath-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - backend

    restart: always

    networks:
      - app-network

  redis:
    image: redis:7-alpine

    container_name: pujapath-redis

    restart: always

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  grafana-data:
